### ISSUE TITLE
TypeError: Cannot read property 'leave' of undefined

### ISSUE THREAD

**Issue by jaumard** [cayasso/primus-rooms#63]
Sometime I have this error for no apparent reason when I do something like `spark.leave('user_room')`: 

I also try an ugly patch like this: 
```
sockets.on('disconnection', spark => {
      if (spark && spark.leave) {
        spark.leave('user_room')
      }
    })
```
But still have the error.
Full error log:
```
/Users/jaumard/LISAProjects/lisa-box/node_modules/primus-rooms/lib/index.js:171
      return this._rooms[fn].apply(this._rooms, arguments);
                        ^

TypeError: Cannot read property 'leave' of undefined
    at Sparky.<anonymous> (/Users/jaumard/LISAProjects/lisa-box/node_modules/primus-rooms/lib/index.js:171:25)
    at Primus.app.sockets.on.spark (/Users/jaumard/LISAProjects/lisa-box/api/services/WebSocketService.js:75:15)
    at Primus.emit (/Users/jaumard/LISAProjects/lisa-box/node_modules/eventemitter3/index.js:137:33)
    at Sparky.end (/Users/jaumard/LISAProjects/lisa-box/node_modules/primus/spark.js:266:12)
    at emitNone (events.js:86:13)
    at Sparky.emit (events.js:185:7)
    at Sparky.end (/Users/jaumard/LISAProjects/lisa-box/node_modules/primus/spark.js:534:8)
    at Timeout.timeout (/Users/jaumard/LISAProjects/lisa-box/node_modules/primus/spark.js:120:11)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

```

Any idea ?

**Comment by lpinca** [comment]
This probably happens because the spark is already closed when you call `spark.leave()`.
What versions of primus and primus-rooms are you using?

**Comment by cayasso** [comment]
Closing do to inactivity!
